import Logo from "@/public/images/Logo.svg"
import heroimage from "@/public/images/heroimage.svg"
import backgroundimage from "@/public/images/backgroundimage.svg"
import cookie from "@/public/images/cookie.png"
import bgcookie from "@/public/images/bgcooki.png"
import aboutImg from "@/public/images/aboutImg.png"
import menuImg1 from "@/public/images/menuImg1.png"
import menuImg2 from "@/public/images/menuImg2.png"
import menuImg3 from "@/public/images/menuImg3.png"
import FindUsBg from "@/public/images/findUsBg.png"
import findUsImg from "@/public/images/findUsImg.png"
import BgCoffeeImg from "@/public/images/BgCoffeeImg.png"
import BrandHighlightBg from "@/public/images/BrandHighlightBg.png"
import BgLocation from "@/public/images/BgLocation.png"
import CategoryImg1 from "@/public/images/CategoryImg1.png"
import CategoryImg2 from "@/public/images/CategoryImg2.png"
import CategoryImg3 from "@/public/images/CategoryImg3.png"
import CategoryImg4 from "@/public/images/CategoryImg4.png"
import TakeABoxBg from "@/public/images/TakeABoxBg.png"
import TakeABoxImg from "@/public/images/TakeABoxImg.png"
import FooterLogo from "@/public/images/FooterLogo.svg"
import FooterBg from "@/public/images/FooterBg.png"

export const landingimages = {Logo, heroimage, backgroundimage,cookie,bgcookie, aboutImg,menuImg1, menuImg2, menuImg3, FindUsBg,findUsImg, BgCoffeeImg, BrandHighlightBg, BgLocation, CategoryImg1, CategoryImg2, CategoryImg3, CategoryImg4, TakeABoxBg, TakeABoxImg,FooterLogo, FooterBg}